pr3/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'pr3.views.home', name='home'),
    # url(r'^login/$', 'pr3.views.supplierlogin', name='login'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^blog/', include('blog.urls')),
    url(r'^subscriber/', include('subscriber.urls')),
    url(r'^supplier/', include('supplier.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

supplier/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:


    url(r'^profile/$', 'supplier.views.supplier_profile', name='supplier-profile'),
    url(r'^profile/api/(?P<id>\d+)/$', 'supplier.views.supplier_profile_json', name='supplier-profile-json'),
    url(r'^profile/info/$', 'supplier.views.supplier_profile', name='supplier-profile'),
    
    url(r'^profile/company/info/$', 'supplier.views.comapny_info', name='comapny-info'),
    url(r'^profile/company/info/api/(?P<supplier_id>\d+)/$', 'supplier.views.comapny_info_json', name='comapny-info-json'),
    
    url(r'^profile/company/revenue/$', 'supplier.views.company_revenue', name='company-revenue'),
    url(r'^profile/company/revenue/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_revenue_json', name='company-revenue-json'),

    url(r'^profile/company/contacts/$', 'supplier.views.company_contacts', name='company-contacts'),
    url(r'^profile/company/licenses/$', 'supplier.views.company_licenses', name='company-licenses'),
    url(r'^profile/company/licenses/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_licenses_json', name='company-licenses-json'),
    url(r'^profile/company/products-services/$', 'supplier.views.company_products_services', name='company-products-services'),
    url(r'^profile/company/products-services/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_products_services_json',
                                                                    name='company-product-services-json'),
    url(r'^profile/company/certification/$', 'supplier.views.company_certification', name='company-certification'),
    url(r'^profile/company/certification/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_certification_json',
                                                                    name='company-certification-json'),


    url(r'^search-corporation/$', 'supplier.views.search_corporation', name='search-corporation'),
    url(r'^search_buyers/$', 'supplier.views.search_buyers', name='search-buyers'),
    url(r'^save_buyers/$', 'supplier.views.save_buyers', name='save-buyers'),
    url(r'^delete_buyer/$', 'supplier.views.delete_buyer', name='delete-buyers'),
    url(r'^add_manual_buyer/$', 'supplier.views.add_manual_buyer', name='add-manual-buyers'),

    url(r'^search/buyer/$', 'supplier.views.search_buyer', name='search-buyer'),
    url(r'^submission-status/$', 'supplier.views.supplier_submission_status', name='submission-status'),

    # url(r'^search-corporation/$', 'supplier.views.search_corporation', name='search-corporation'),
    
)

supplier/models.py
from django.db import models
from django.contrib.auth.models import User
from supplier.choices import *
from decimal import Decimal
# Create your models here.
class ProductAndServiceCategory(models.Model):
    '''
    Product category 
    '''
    category_name = models.CharField(max_length=256, blank=True, null=True, verbose_name='Category Name')

    def __unicode__(self):
        return self.category_name

class ProductServiceCode(models.Model):
    '''
    This model will take SIC, NAICS etc code.
    code_type = SERVICE_CODE_TYPE
    '''
    code = models.CharField(max_length=50, blank=True, null=True, verbose_name='Code', unique=True)
    code_type = models.CharField(max_length=15, choices=SERVICE_CODE_TYPE, blank=True, null=True, verbose_name='Code Type')
    title = models.CharField(max_length=50, blank=True, null=True, verbose_name='Title')
    common_keywords = models.CharField(max_length=200, blank=True, null=True, verbose_name='Common Keywords')
    category = models.ForeignKey(ProductAndServiceCategory, blank=True, null=True)

    def __unicode__(self):
        return "%s: %s" % (self.code_type, self.code)


class Buyer(models.Model):
    company_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Company Name')
    login_url = models.URLField(max_length=256, blank=True, null=True, verbose_name='Login Url')
    registration_url = models.URLField(max_length=256, blank=True, null=True, verbose_name='Registration Url')
    buyer_introduction = models.CharField(max_length=500, blank=True, null=True, verbose_name='Buyer Introduction')
    state = models.CharField(max_length=100, blank=True, null=True, verbose_name='State')
    ps_buy_code = models.ManyToManyField(ProductServiceCode, blank=True, null=True, related_name='comp_buy_codes')
    product_service_category = models.ManyToManyField(ProductAndServiceCategory, blank=True, null=True)

    def __unicode__(self):
        return self.company_name

class Supplier(models.Model):
    user = models.OneToOneField(User)
    salutation = models.CharField(max_length=5, blank=True, null=True, verbose_name='Salutation')
    first_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='First Name')
    last_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Last Name')
    position = models.CharField(max_length=50, blank=True, null=True, verbose_name='Position')
    phone_number = models.CharField(max_length=25, blank=True, null=True, verbose_name='Phone Number')
    fax_number = models.CharField(max_length=25, blank=True, null=True, verbose_name='Fax Number')
    cell_number = models.CharField(max_length=25, blank=True, null=True, verbose_name='Cell Number')
    contact_email = models.EmailField(blank=True,null=True, verbose_name='Contact E-Mail')
    contact_address = models.CharField(max_length=500, blank=True,null=True, verbose_name='Contact Address')
    country = models.CharField(max_length=50, blank=True, null=True, verbose_name='Country')
    state = models.CharField(max_length=50, blank=True, null=True, verbose_name='State')
    city = models.CharField(max_length=50, blank=True, null=True, verbose_name='City')
    zip_code = models.CharField(max_length=15, blank=True, null=True, verbose_name='Zip Code')
    method_of_notification = models.CharField(max_length=10, blank=True, null=True, verbose_name='Method of Notification')
    preferred_password = models.CharField(max_length=128, blank=True, null=True, verbose_name='Password')
    subscription_status = models.CharField(max_length=10, blank=True, null=True, verbose_name='Subscription Status')
    subscription_date = models.DateField(blank=True, null=True)
    subscription_expire_date = models.DateField(blank=True, null=True)
    profile_completion_status = models.CharField(max_length=10, blank=True, null=True, verbose_name='Profile Completion Status') 

    def __unicode__(self):
        return str(self.id)

    def get_profile_completion_status_redirect_url(self):
        if int(self.profile_completion_status) == 1:
            redirect_url = "/supplier/profile/company/revenue/"
        elif int(self.profile_completion_status) == 2:
            redirect_url = "/supplier/profile/company/contacts/"
        elif int(self.profile_completion_status) == 3:
            redirect_url = "/supplier/profile/company/licenses/"
        elif int(self.profile_completion_status) == 4:
            redirect_url = "/supplier/profile/company/products-services/"
        elif int(self.profile_completion_status) == 5:
            redirect_url = "/supplier/profile/company/certification/"
        elif int(self.profile_completion_status) == 6:
            redirect_url = "/supplier/submission-status/"
        elif int(self.profile_completion_status) == 0:
            redirect_url = "/supplier/profile/company/info/"
        elif int(self.profile_completion_status) == -1:
            redirect_url = "/supplier/profile/info/"
        else:
            redirect_url = "/supplier/submission-status/"

        return redirect_url

    def is_profile_complete(self):
        if self.salutation == None or self.salutation == '':
            return False
        elif self.first_name == None or self.first_name == '':
            return False
        elif self.last_name == None or self.last_name == '':
            return False
        elif self.position == None or self.position == '':
            return False
        elif self.phone_number == None or self.phone_number == '':
            return False
        elif self.cell_number == None or self.cell_number == '':
            return False
        elif self.contact_email == None or self.contact_email == '':
            return False
        elif self.contact_address == None or self.contact_address == '':
            return False
        elif self.country == None or self.country == '':
            return False
        elif self.state == None or self.state == '':
            return False
        elif self.city == None or self.city == '':
            return False
        elif self.preferred_password == None or self.preferred_password == '':
            return False
        else:
            return True


    def get_full_name(self):
        name = self.salutation
        if self.first_name:
            name += " " + self.first_name
        if self.last_name:
            name += " " + self.last_name
        return name

class CompanyCapabilityStatement(models.Model):
    capability_statement = models.TextField(max_length=250, blank=True, null=True, verbose_name='Capability Statement')
    upload_doc = models.FileField(blank=True, null=True, verbose_name='Document Upload',
        upload_to='attachment/doc')
    upload_video = models.CharField(max_length=250, blank=True, null=True)

    def __unicode__(self):
        return "%s" % (self.capability_statement[:20])
   

class Address(models.Model):
    address_title = models.CharField(max_length=200, blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    zip_code = models.CharField(max_length=50, blank=True, null=True)
    address_type = models.CharField(max_length=5, blank=True, null=True)

    def __unicode__(self):
        return "%s->%s" % (self.country, self.city)


class SupplierCompany(models.Model):
    supplier = models.OneToOneField(Supplier)
    comp_name = models.CharField(max_length=200, blank=True, null=True, verbose_name='Legal Company Name')
    organization_type = models.CharField(max_length=50, blank=True, null=True, verbose_name='Organization Type')
    doing_business_as = models.CharField(max_length=200, blank=True, null=True, verbose_name='DBA Company Name')
    tax_id_number = models.CharField(max_length=50, blank=True, null=True, verbose_name='Federal Tax ID')
    social_security_number = models.CharField(max_length=50, blank=True, null=True, verbose_name='Social Security Number')
    comp_dunn_street = models.CharField(max_length=50, blank=True, null=True, verbose_name='Dunn & Brad Street Number')
    comp_phone = models.CharField(max_length=20, blank=True, null=True, verbose_name='Company Phone Number')
    comp_fax = models.CharField(max_length=20, blank=True,null=True, verbose_name='Company Fax Number')
    comp_url = models.CharField(max_length=100, blank=True,null=True, verbose_name='Company Website (URL)')
    corporate_email = models.EmailField(blank=True,null=True, verbose_name='Corporate E-Mail')
    year_established = models.DateField(max_length=15,null=True, blank=True, verbose_name='Year Business was Established')
    num_of_employees = models.CharField(max_length=10,null=True, blank=True, verbose_name='Number Of Employees')
    # country = models.CharField(max_length=96, blank=True, null=True, verbose_name='Country')
    # state = models.CharField(max_length=96, blank=True, null=True, verbose_name='State')
    capability = models.ForeignKey(CompanyCapabilityStatement, blank=True, null=True)
    ps_categories = models.ManyToManyField(ProductAndServiceCategory, blank=True, null=True)
    product_service_description = models.TextField(max_length=200, blank=True,null=True, verbose_name='Product & Service Description')
    comp_logo = models.ImageField(blank=True, null=True, verbose_name='Current Company Logo', 
        upload_to='attachment/company/')
    comp_picture = models.ImageField(blank=True, null=True, verbose_name='Current Company/Personal Picture',
        upload_to='attachment/company/')
    comp_address = models.ForeignKey(Address, blank=True, null=True)

    def __unicode__(self):
        return str(self.id)
    


class CompanyRevenue(models.Model):
    company = models.OneToOneField(SupplierCompany)
    last_year_annual_sale = models.CharField(max_length=10, blank=True, null=True)

supplier/forms.py
from django import forms
from supplier.models import *

class ProfileForm(forms.ModelForm):

	class Meta:
		model = Supplier
		exclude = ['subscription_status', 'profile_completion_status']


class CompInfoForm(forms.ModelForm):
	class Meta:
		model = SupplierCompany


class CapabilityForm(forms.ModelForm):
	class Meta:
		model = CompanyCapabilityStatement


class RevenueForm(forms.ModelForm):
	class Meta:
		model = CompanyRevenue
		exclude = ['company',]

class AddressForm(forms.ModelForm):
	class Meta:
		model = Address

class CompanyLicenseForm(forms.ModelForm):
	class Meta:
		model = CompanyLicense
        exclude = ['company',]

class CompanyCertificationForm(forms.ModelForm):
	class Meta:
		model = CompanyCertification
        exclude = ['company',]

class CertificateNameForm(forms.ModelForm):
	class Meta:
		model = CertificateName
        exclude = ['display_order','active']

class CompanyProductServiceForm(forms.ModelForm):
    class Meta:
        model = CompanyProductService
        exclude = ['company',]

templates/supplier/comapny_info.html
{% extends "layout.html" %}

{% block container %}
	{% include "steps.html" %}

	{% include "supplier/form/company_info_form.html" %}	
{% endblock %}

{% block page_js %}
<script type="text/javascript">
$('#pre-selected-options').multiSelect({
    selectableHeader: "<div class='bg-danger'>Selectable Category</div>",
    selectionHeader: "<div class='bg-danger'>Selected Category</div>"
});


pr.controller('CompInfoController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Supplier Company profile controller...");
        var sup_id = $("#id_supplier").val();
        var url = "/supplier/profile/company/info/api/"+sup_id+"/"
        $http({method: 'GET', url: url}).
            success(function(data, status, headers, config) {
                console.log(data);
                $scope.comp = data;
                $scope.capability = data.capability
                
        }).error(function() {
            console.log("no company info")
        });
    }
    $scope.init();

}]);

</script>
{% endblock %}

templates/supplier/comp_cert_form.html
<table class="table certificate">
<form method="post" action="/supplier/profile/company/certification/">{% csrf_token %}
<thead>
	<tr>
		<th>SR#</th>
		<th>Certification Description</th>
		<th>Cert. Number</th>
		<th>Category</th>
		<th>Cert Date</th>
		<th>Expiration Date</th>
		<th width="100">How many years have you had this certification?</th>
		<th>Upload certification</th>
	</tr>
</thead>

<tbody>
	
	<input type="hidden" name="company" value="{{company_id}}">
	{% for cert in cert_names %}
	<tr>
		<td>
			{{cert.id}}
			<input type="hidden" name="certificate_name" value="{{cert.id}}">
		</td>
		<td width="200">
			{{cert.cert_name}}
		</td>
		<td><input type="text" name="cert_number" class="form-control" value="{{cert.company_cert.cert_number}}"></td>
		<td><input type="text" name="category" class="form-control" value="{{cert.company_cert.category}}"></td>
		<td><input type="text" name="certification_date" class="form-control datetime" value="{{cert.company_cert.certification_date}}"></td>
		<td><input type="text" name="expire_date" class="form-control datetime" value="{{cert.company_cert.expire_date}}"></td>
		<td><input type="text" name="certificate_duration" class="form-control" value="{{cert.company_cert.certificate_duration}}"></td>
		<td><input type="file" name="upload_certificate" class="form-control" value="{{cert.company_cert.upload_certificate}}"></td>
	</tr>
	{% endfor %}
	<tr>
		<td colspan="8">
			<button class="btn btn-primary">Submit & Continue</button>
		</td>
	</tr>
	
</tbody>

	

</form>
</table>

templates/supplier/company_certification.html
{% extends "layout.html" %}

{% block container %}
	{% include "steps.html" %}

	{% include "supplier/comp_cert_form.html" %}	

{% endblock %}

{% block page_js %}
<script type="text/javascript">


pr.controller('CompCertController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Supplier Company cert controller...");
    }
    $scope.init();

}]);

</script>
{% endblock %}

templates/supplier/company_contacts.html
{% extends "layout.html" %}

{% block container %}
	{% include "steps.html" %}

	{% include "supplier/form/company_contact_form.html" %}	
{% endblock %}

{% block page_js %}
<script type="text/javascript">
$('#pre-selected-options').multiSelect({
    selectableHeader: "<div class='bg-danger'>Selectable Category</div>",
    selectionHeader: "<div class='bg-danger'>Selected Category</div>"
});


pr.controller('CompContactController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Supplier Company Contact controller...");
        var sup_id = $("#id_supplier").val();
        var url = "/supplier/profile/company/contact/api/"+sup_id+"/"
        $http({method: 'GET', url: url}).
            success(function(data, status, headers, config) {
                console.log(data);
                $scope.comp = data;
                $scope.capability = data.capability
                
        }).error(function() {
            console.log("no company info")
        });
    }
    $scope.init();

}]);

</script>
{% endblock %}

templates/supplier/company_products_services.html
{% extends "layout.html" %}

{% block container %}
	{% include "steps.html" %}
	{% include "supplier/form/company_product_service_form.html" %}
{% endblock %}

{% block page_js %}
<script type="text/javascript">

pr.controller('CompProServiceController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Supplier Company Product Service controller...");
        var sup_id = $("#id_supplier").val();
        var url = "/supplier/profile/company/products-services/api/"+sup_id+"/"
        console.log("Supplier ID => " + sup_id)
        console.log("Url => " + url)
        $http({method: 'GET', url: url}).
            success(function(data, status, headers, config) {
                console.log(data);
                $scope.comp_pro_service = data;

        }).error(function() {
            console.log("no company info")
        });
    }
    $scope.init();

}]);

</script>
{% endblock %}

templates/supplier/company_revenue.html
{% extends "layout.html" %}

{% block container %}
	{% include "steps.html" %}

	{% include "supplier/form/company_revenue_form.html" %}	
{% endblock %}

{% block page_js %}
<script type="text/javascript">

pr.controller('CompRevController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Supplier Company Revenue controller...");
        var sup_id = $("#id_supplier").val();
        // var url = "/supplier/profile/company/revenue/api/"+sup_id+"/"
        // $http({method: 'GET', url: url}).
        //     success(function(data, status, headers, config) {
        // });
    }
    $scope.init();

}]);

</script>
{% endblock %}

templates/supplier/left-menu.html
<div class="list-group" ng-controller="LeftMenuController">
  <a  class="list-group-item" id='profile-list' href="/supplier/profile/">
    Profile
  </a>
  <div id="collapseOne" class="profile">
    <a href="/supplier/profile/info/" class="list-group-item">Supplier Information</a>
    <a href="/supplier/profile/company/info/" class="list-group-item">Company Information</a>
    <a href="/supplier/profile/company/revenue/" class="list-group-item">Company Revenue</a>
    <a href="/supplier/profile/company/contacts/" class="list-group-item">Company Contact Info</a>
    <a href="/supplier/profile/company/licenses/" class="list-group-item">Licenses & Certifications</a>
    <a href="/supplier/profile/company/products-services/" class="list-group-item">Product & Services</a>
    <a href="/supplier/profile/company/certification/" class="list-group-item" ng-click="ActiveMenu($event)">Certification</a>
  </div>
  <a href="/supplier/search-corporation/" class="list-group-item">Search Corporation</a>
  <a href="#" class="list-group-item">Membership</a>
  <a href="#" class="list-group-item">Advanced Search</a>
  <a href="#" class="list-group-item">Corporation Update</a>
  <a href="#" class="list-group-item">Capability Statement</a>
  <a href="/supplier/notification/" class="list-group-item">Notifications</a>
  <a href="/supplier/submission-status/" class="list-group-item">Submission Status</a>
</div>

templates/supplier/right-side-content.html
<div class='col-md-12 content'>           

    <form name='corporations'>{% csrf_token %}
        <div class='row'>
            <div class='col-md-5 form-element'>
                <h1>List of Product & Services Category</h1>
                <select name="multiple" id='select1' multiple class="form-control">
                    {% for category in categories %}
                        <option value="{{ category.pk }}">{{ category.category_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class='col-md-2' style="padding-top: 60px; text-align: center">
                <button type="button" id="moveright" class="btn btn-default "> >> </button><br>
                <button type="button" id="moveleft" class="btn btn-default form-element"> << </button>
            </div>

            <div class='col-md-5 form-element'>
                <h1>Selected Category</h1>
                <select name="categories" id='select2' multiple class="form-control">

                </select>
            </div>

        </div>

        <div class='row' style="margin-top: 30px;">
            <div class="col-md-12" style="margin-bottom: 10px;">
                <p class="text-danger"><strong>Add comma seperated (,) keywords to search corporations</strong>
                <span style="color:#000; margin-left: 20px;">example: computer, textile, food </span> </p>
            </div>
            <div class='col-md-12'>
                <input type="text" cols="40" rows="5" id="findcat" class="form-control" placeholder="Find category">
            </div>
            <div class="col-md-12" style="margin: 20px auto 10px;">
                <p class="text-danger"><strong>Add comma seperated (,) corporations name to search corporations</strong>
                <span style="color:#000; margin-left: 20px;">example: computer, textile, food </span> </p>
            </div>
            <div class='col-md-12 form-element'>
                <input type="text" cols="40" rows="5" id="findbuyer" class="form-control" placeholder="Find corporation">
            </div>
        </div>

        <div class='row'>
            <div class='col-md-9 form-element' style="margin: 20px auto 10px;">
                <input type='radio' value='yes' name='showall' checked='true'> Show all
                <input type='radio' value='no' name='showall'> Do not show already selected 
            </div>
            <div class='col-md-3 form-element' style="margin: 20px auto 10px; text-align:right; ">
                <button type="button" id="search" class="btn btn-danger"> Search Corporation </button> 
            </div> 
        </div>
      
    </form>

    <div class='row'>
        <div class='col-md-12' id="loader">
            <img src="/static/images/loader.gif">
        </div> 
        <div class='col-md-12 form-element' id="buyers">


        </div> 
    </div>
    <!-- Search result-->
    <div class='row bysearch'>
              
        <div class="col-md-12">
            <div id='selectedbuyers'>
                <div class="alert alert-info tb-header">
                    <p>Selected List of Corporations</p>
                </div>
                <table class="table table-striped table-hover  table-bordered">
                    <thead>
                        <tr>
                            <th width=7%><div align='center'>Sr.#<div></th>
                            <th width=45%>Corporation Name</th>
                            <th width=38%>State</th>
                            <th width=10%><div align='center'>Delete</div></th>
                        </tr>     
                    </thead>
                    <tbody>
                      
                        {% include "supplier/selected_buyers.html" %}
                      
                    </tbody>

                </table>
              
            </div>
        </div>
    </div>
    <!-- -->
    <!-- -->
    <div class='row'>
      <div class='col-md-12 form-element'>
        
        <div class="panel panel-info tb-header">
            <div class="panel-heading">
                Add Corporation / Corporations Manually
            </div>
            <div class="panel-body">
                <form name="manual-add-corp" role="form">
                <table class="table">
                    <tr>
                        <td colspan="2">
                            <p> The buyers/corporations which you could not find in search and you want submission with them, please add company name below. We will provide submission facility for your added companies.
                            </p>        
                        </td>
                    </tr>
                    <tr>
                        <td width="25%">
                            <label class="" for="search-buyer">Corporations Name:</label>
                        </td>
                        <td width="75%" class="hello">
                            <div class="input-group ">
                                <input type="text" class="form-control" ng-model="search_buyer" id="manualbuyers" ng-change="searchBuyer(search_buyer)">
                                <span class="input-group-btn">
                                    <button id="add-manual-buyer" type="button" class="btn btn-danger">Add Corporation</button>
                                </span>
                            </div>
                            <span ng-show="no_buyers_found">No buyers found yet</span>
                            <div class="display_buyers" ng-show="show_buyers_list">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Buyers Name</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr ng-repeat="buyer in buyers.results" ng-click="selectBuyer(buyer)">
                                            <td>{[{ buyer.id }]}</td>
                                            <td>{[{ buyer.company_name }]}</td>
                                        </tr>  
                                    </tbody>
                                </table>
                            </div>
                            
                        </td>
                    </tr>
                </table>
                </form>
          </div>
        
        </div>

      </div> 
    </div>
    

    <div class='row manualadd'>
              
      <div class="col-md-12">
        <div id='mbuyers'>
          
        </div>
      </div>
    
  
    </div>

    
    </div>
    <a class="btn btn-primary" href="/supplier/profile/info/">Save & Continue </a>
</div>



<script type="text/javascript">


(function(){
$("#loader").hide();
    $("#search").on('click', function(event){

        $("#buyers").show();
        $("#loader").show();
        var cat_vals = [];
        $('select#select2 option').each(function() {
          cat_vals.push($(this).val());
        });
        categories = cat_vals.join(", ");
        // console.log(cat_vals);
        
        //categories = $("select[name='categories'] option").serialize();
        showall = $("input:radio[name='showall']:checked").val();
        findbuyer = $("#findbuyer").val();
        findcat = $("#findcat").val();
        console.log(showall + ', '+findbuyer+', '+findcat);
        
        $.ajax({
            type: "POST",
            url: "/supplier/search_buyers/",
            data: {
              'categories': categories,
              'showall': showall,
              'findbuyer': findbuyer,
              'findcat': findcat
            },

            success: function(data) {
                $("#loader").hide();
                $("#buyers").html(data);
            },
            error: function(result) {

            }
        });
        

        event.preventDefault();
    });

    $("#moveright").click(function(){
      
      return !$('#select1 option:selected').remove().appendTo('#select2'); 
      
    })

    $('#moveleft').click(function() {  
      return !$('#select2 option:selected').remove().appendTo('#select1');  
    }); 

/*
======================== Add manual buyers =========
*/
 

/*

======================== Here goes manually searching buyers with auto suggession=========

*/


})(jQuery);

</script>

</div>

templates/supplier/submission-status.html
<table class="table" ng-controller="SubpplierSubmissionController">
<thead>
	<tr>
		<th>Buyer ID</th>
		<th>Buyer Name</th>
		<th>Registration URL</th>
		<th>Submission Status</th>
		<th>Submission Date</th>
	</tr>
</thead>
<tbody>
	<tr ng-repeat="buyer in buyers">
		<td>{[{ buyer.id }]}</td>
		<td>{[{ buyer.company_name }]}</td>
		<td>{[{ buyer.buyer.registration_url }]}</td>
		<td>{[{ buyer.selection_date }]}</td>
		<td>{[{ buyer.submission_status }]}</td>
		<td>{[{ buyer.submission_date }]}</td>
	</tr>
	<tr ng-show="!buyers">
		<td colspan="6">No buyers yet to submission</td>
	</tr>
</tbody>
</table>

templates/supplier/supplier_profile.html
{% extends "layout.html" %}

{% block container %}
	{% include "steps.html" %}

	{% include "supplier/form/profile_form.html" %}	
{% endblock %}

{% block page_js %}
<script type="text/javascript">
	
pr.controller('SupplierProfileController',['$scope', '$http', function ($scope, $http) {
    $scope.init = function(){
        console.log("Supplier profile controller...");
        var sup_id = $("#id_supplier").val();
        var url = "/supplier/profile/api/"+sup_id+"/"
        $http({method: 'GET', url: url}).
            success(function(data, status, headers, config) {
                $scope.supplier = data.fields;
                $("#salutation").val(data.fields.salutation);
                $("#id_zip_code").val(data.fields.zip_code)
                $("input:radio[name='notification']").filter('[value="'+data.fields.method_of_notification+'"]').attr('checked', true);
                
        });
    }
    $scope.init();

}]);

</script>
{% endblock %}