pr3/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'pr3.views.home', name='home'),
    # url(r'^login/$', 'pr3.views.supplierlogin', name='login'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^blog/', include('blog.urls')),
    url(r'^subscriber/', include('subscriber.urls')),
    url(r'^supplier/', include('supplier.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

subscriber/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^login/$', 'subscriber.views.supplier_login', name='subscriber-login'),
    url(r'^logout/$', 'subscriber.views.supplier_logout', name='subscriber-logout'),
    
    url(r'^registration/$', 'subscriber.views.registration', name='registration'),
    url(r'^registration/(?P<activation_code>[\w]+)/active/$', 'subscriber.views.registration_active', name='registration-active'),
    url(r'^(?P<uid>\d+)/registration/success/$', 'subscriber.views.registration_success', name='registration-success'),

    url(r'^get-started/$', 'subscriber.views.get_started', name='get-started'),

    url(r'^get-coupon/(?P<code>[\w]+)/$', 'subscriber.views.get_coupon', name='get-coupon'),

    # url(r'^payment/$', 'supplier.views.payment', name='payment'),
    url(r'^payment/create/$', 'subscriber.views.payment_create', name='payment_create'),
    url(r'^payment/execute/$', 'subscriber.views.payment_execute', name='payment_execute'),
    url(r'^payment/success/$', 'subscriber.views.payment_success', name='payment_success'),

)

subscriber/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from supplier.models import *
# Create your models here.
from choices import PLAN_FREQUENCY


class Service(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Service Title')
    display_order = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return self.name


class Package(models.Model):
    package_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Package Name')
    display_order = models.IntegerField(blank=True, null=True)
    active = models.BooleanField(default=True)
    services = models.ManyToManyField(Service)

    def __unicode__(self):
        return self.package_name

class Frequency(models.Model):
    '''
    duration = "MONTHLY, YEARLY, HALF-YEARLY, QUARTERLY"
    '''
    duration_title = models.CharField(max_length=50, choices=PLAN_FREQUENCY, blank=True, null=True)
    # standared_price = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    display_order = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        return dict(PLAN_FREQUENCY)[self.duration_title]

    @classmethod
    def get_number(self):
        return self.duration_title

class PackagePlan(models.Model):
    frequency = models.ForeignKey(Frequency)
    package = models.ForeignKey(Package)
    price = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)

    def __unicode__(self):
        return str(self.id)

class CouponCode(models.Model):
    code = models.CharField(max_length=50, blank=True, null=True, unique=True)
    date_created = models.DateTimeField(auto_now_add=True)
    expire_date = models.DateTimeField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    '''
    status = NotUsed, Used, Expired
    '''
    status = models.CharField(max_length=10, blank=True, null=True)
    discount_amount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    '''
    discount type will have two option (percent, fixed) valud 0 for fiexed amount and 1 for percent
    '''
    discount_type = models.CharField(max_length=2, choices=(('0', 'Fixed'), ('1', 'Percent')),
        blank=True, null=True)

    def __unicode__(self):
        return self.code

class CouponSupplier(models.Model):
    coupon = models.ForeignKey(CouponCode, blank=True, null=True)
    subscriber = models.ForeignKey(User, blank=True, null=True)
    date_time = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        return "%s %s" % (self.coupon, self.subscriber)

class Subscription(models.Model):
    user = models.ForeignKey(User)
    package_plan = models.ForeignKey(PackagePlan)
    subscription_date = models.DateTimeField(auto_now_add=True)
    expire_date = models.DateTimeField(blank=True, null=True)
    coupon_used = models.ForeignKey(CouponCode, blank=True, null=True)
    plan_amount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    net_amount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    '''
        subscription_status = 0 for active, 1 for expired
    '''
    subscription_status = models.CharField(max_length=10, blank=True, null=True)

class ActivationCode(models.Model):
    '''
    status = 0, for newly created code
    status = 1, when a code is used
    status = 2, when code is not used and put in inactive state
    status = 3, when a code is not used before the expire time

    # deafault expire date is 48 hours from the creation date
    '''
    user = models.ForeignKey(User, blank=True, null=True)
    code = models.CharField(max_length=200, unique=True)
    creation_date = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    expire_date = models.DateTimeField(default=datetime.now()+timedelta(days=2), blank=True, null=True)
    ACTIVATION_STATUS = ((0,"ACTIVE"), (1,"USED"), (2,"INACTIVE"), (3,"EXPIRED"))
    status = models.IntegerField(choices=ACTIVATION_STATUS)
    CODE_FOR = ((1,"PASSWORD_RESET"), (0,"USER_REGISTER"))
    code_for = models.IntegerField(choices=CODE_FOR, blank=True, null=True)

    def __unicode__(self):
        return self.code

    def is_expired(self):
        return self.expire_date > datetime.now()

    def is_active(self):
        return self.status == 0


class PaymentHistory(models.Model):
    supplier = models.ForeignKey(Supplier)
    plan = models.ForeignKey(PackagePlan)
    plan_amount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    net_amount = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    coupon = models.ForeignKey(CouponCode, blank=True, null=True)

    payment_id = models.CharField(max_length=100, blank=True, null=True)
    transaction = models.CharField(max_length=500, blank=True, null=True)
    payment_status = models.CharField(max_length=10, blank=True, null=True)
    create_time = models.DateTimeField(blank=True, null=True)
    token = models.CharField(max_length=100, blank=True, null=True)

    def __unicode__(self):
        return "%s : %f" % (self.supplier.first_name, self.net_amount)

subscriber/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from forms import RegistrationForm, PasswordResetForm
from django.contrib.auth.models import User
from django.contrib import auth, messages
from django.core import serializers
import json
from datetime import datetime, timedelta
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from paypalrestsdk import Payment
import logging
import paypalrestsdk

# Create your views here.
from subscriber.models import *

def supplier_login(request):
    if request.method == "POST":
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        
        if user is not None:
            auth.login(request, user)
            if user.is_active and user.is_staff:
                return HttpResponseRedirect("/superadmin/")
            elif user.is_active and not user.is_staff:
                try:
                    supplier = Supplier.objects.get(user=user)
                    redirect_url = supplier.get_profile_completion_status_redirect_url()
                except Supplier.DoesNotExist:
                    return HttpResponseRedirect("/subscriber/get-started/")
                return HttpResponseRedirect(redirect_url)
            else:
                messages.warning(request, "User %s not active yet" % (username))
                return HttpResponseRedirect("/")
        else:
            messages.warning(request, "User %s does not exits" % (username))
            return HttpResponseRedirect("/")
    else:
        return render(request, "subscriber/supplier-login.html", {})
@login_required
def supplier_logout(request):
    auth.logout(request)
    return HttpResponseRedirect("/")


def registration(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST, request=request)
        if form.is_valid():
            form.save()
            
            return HttpResponseRedirect("/")
        else:
            return render(request, "subscriber/supplier-registration.html", {})            
    else:

        return render(request, "subscriber/supplier-registration.html", {})


def registration_active(request, activation_code):
    try:
        ac = ActivationCode.objects.get(code=activation_code, status=0, code_for=0)
        ac.status = 1
        ac.save()
        newuser = ac.user
        newuser.is_active = True
        newuser.save()
        return HttpResponseRedirect("/subscriber/"+str(newuser.id)+"/registration/success/")
    except Exception, e:
        ac = ActivationCode.objects.get(code=activation_code, code_for=0)
        if ac.is_expired:
            messages.add_message(request, messages.INFO, "Activation time is expired")
        elif ac.is_active:
            messages.add_message(request, messages.INFO, "Your account is inactive.")
        return HttpResponseRedirect("/")
    

def registration_success(request, uid):
    requested_user = User.objects.get(id=uid)
    requested_user.backend = 'django.contrib.auth.backends.ModelBackend'
    auth.login(request, requested_user)
    try:
        supplier = Supplier.objects.get(user=requested_user)
        redirect_url = supplier.get_profile_completion_status_redirect_url()
    except Supplier.DoesNotExist:
        return HttpResponseRedirect("/supplier/get-started/")
    return HttpResponseRedirect(redirect_url)



@login_required
def get_started(request):
    # import pdb; pdb.set_trace();
    packages = Package.objects.filter(active=1).order_by("display_order")
    services = Service.objects.all()
    package_plans = PackagePlan.objects.all()
    frequencies = Frequency.objects.all()


    return render(request, "subscriber/get_started.html", 
        {'packages': packages, 'services': services, 'package_plans': package_plans, 
        'frequencies': frequencies})


def get_package_plan(request, ppid):
    pass
    

def get_coupon(request, code):
    try:
        coupon = CouponCode.objects.get(code=code)
        if coupon.expire_date > timezone.now() and coupon.status == '0':
            data = serializers.serialize("json", [coupon,]) 
            struct = json.loads(data)
            data = json.dumps(struct)
            return HttpResponse(data, content_type='application/json')
        elif coupon.expire_date < timezone.now():
            return HttpResponse("Expired")
        elif coupon.status == '1':
            return HttpResponse("Used")
        else:
            return HttpResponse("")
        
    except CouponCode.DoesNotExist:
        return HttpResponse("DoesNotExist")
        

@csrf_exempt
@login_required
def payment_create(request):
    #import pdb; pdb.set_trace();
    user = request.user
    plan_id = request.POST['ppid']
    plan_amount = request.POST['plan_amount']
    net_amount = request.POST['net_amount']
    coupon_code = request.POST['ccid']

    
    plan = PackagePlan.objects.get(pk=plan_id)
    if coupon_code != '0':
        cc = CouponCode.objects.get(pk=coupon_code)
    else:
        cc = None

    try:
        supplier, created = Supplier.objects.get_or_create(user=user)
        supplier.subscription_status = 0
        supplier.save()
    except Exception, e:
        raise e
    
    '''
    paypalrestsdk.configure({
        "mode": "sandbox", 
        "client_id": "AXD1xxBNG1VP1KO9j3PRAJmibtCGuNN7Zjry-5rIeE1UBZMjBEq6EqUiesOv",
        "client_secret": "EBINrBDb5Xl_jdkw2QeiwhLhN5TOZwFWQNOwhlbiyldIptJ8SxYtANUr3FHJ" 
    })
    site = request.META['HTTP_HOST']

    payment = paypalrestsdk.Payment({
        "intent": "sale",
        "payer": {
            "payment_method": "paypal"
        },
        "redirect_urls": {
        "return_url": "http://"+ site +"/payment/execute",
        "cancel_url": "http://"+ site +"/" },
        "transactions": [{
        "item_list": {
        "items": [{
            "name": plan.package.package_name,
            "sku": plan_id,
            "price": net_amount,
            "currency": "USD",
            "quantity": 1 }]},
            "amount": {
            "total": net_amount,
            "currency": "USD" },
            "description": "This is the payment transaction description." 
        }]
    })

    if payment.create():
        print("Payment[%s] created successfully" % (payment.id))
        ph = PaymentHistory(supplier=sp, plan=plan, plan_frequency=plan_frequesncy, plan_amount=plan_amount,
                   net_amount=net_amount)
        ph.payment_id = payment.id
        ph.payment_status = payment.state
        ph.payer_id = payment.create_time
        ph.create_time = payment.create_time
        
        # Redirect the user to given approval url
        for link in payment.links:
            if link.method == "REDIRECT":
                redirect_url = link.href
                query = parse_qs(urlparse(redirect_url).query)
                token = query['token'][0]
                ph.token = token
                ph.save()
        
        return redirect(redirect_url)
    else:
        print("Error while creating payment:")
        print(payment.error)
    
    return HttpResponse("Hello world!")
    return HttpResponseRedirect("/payment/error/")
    '''
    ph = PaymentHistory()
    ph.supplier = supplier
    ph.plan = plan
    if cc:
        ph.coupon = cc

    else:
        ph.coupon = None
    ph.plan_amount = plan_amount
    ph.net_amount = net_amount
    ph.token = '1232323232412'
    ph.save()
    return HttpResponseRedirect("/subscriber/payment/execute/")
    
@login_required
def payment_execute(request):
    sp = Supplier.objects.get(user=request.user)
    token = '1232323232412'
    ph = PaymentHistory.objects.get(token=token, supplier=sp)
    ph.payment_status = 'completed'
    ph.save()

    if ph.coupon:
        cs = CouponSupplier(coupon=ph.coupon, subscriber=sp.user, date_time=datetime.now())
        cs.save()

    subs = Subscription(user=sp.user, package_plan=ph.plan)
    subs.expire_date = datetime.now()+timedelta(days=int(ph.plan.frequency.duration_title))
    subs.plan_amount = ph.plan_amount
    subs.net_amount = ph.net_amount
    subs.subscription_status = 0
    subs.save()

    sp.subscription_status = 1
    sp.profile_completion_status = -1
    sp.save()

    return HttpResponseRedirect("/subscriber/payment/success/")

'''
    payer_id = request.GET['PayerID']
    token = request.GET['token']
    
    sp = Supplier.objects.get(supplier_user=request.user)
    ph = PaymentHistory.objects.get(token=token, supplier=sp)
    
    paypalrestsdk.configure({
        "mode": "sandbox", # sandbox or live
        "client_id": "AXD1xxBNG1VP1KO9j3PRAJmibtCGuNN7Zjry-5rIeE1UBZMjBEq6EqUiesOv",
        "client_secret": "EBINrBDb5Xl_jdkw2QeiwhLhN5TOZwFWQNOwhlbiyldIptJ8SxYtANUr3FHJ" 
    })
    
    payment = paypalrestsdk.Payment.find(ph.payment_id)
    
    if payment.execute({"payer_id": payer_id}):
        print("Payment execute successfully")
        ph.payment_status = 'completed'
        ph.save()
    else:
        print(payment.error) # Error Hash
    messages.success(request, 'Your payment is successfully loaded.')
    return HttpResponseRedirect("/ssm/buyer/")
'''

def payment_success(request):
    return HttpResponseRedirect("/supplier/search-corporation/")

templates/subscriber/get_started.html
{% extends "layout.html" %}

{% block page_css %}
<style type="text/css">
table.plan thead tr {
	background-color: #333;
	color: #FFF;
}
table.plan {
	border: 1px solid #333;
}
table.plan tr td {
	border-right: 1px solid #333;
}
table.plan tr td.custom-border {
	
	text-align: center;
}
table.payment h1 {
	font-size: 26px !important;
	color: #000;
}
</style>
{% endblock %}

{% block full_container %}
<div class="container">
	<div class="row">
			{% include 'top-menu.html' %}
	</div>	
	
	<div class="row mainbody" style="margin-top: 20px;">
		
		<div class="col-md-12" ng-controller="GetStartedController">
			{% block container %}
				<div class='row'>
					{% include "steps.html" %}
				</div>
				<div class='row'>
					{% include "subscriber/plan.html" %}
				</div>
				<div class='row'>
					{% include "subscriber/payment-details.html" %}
				</div>
			{% endblock container %}
		</div>
	</div>
	
</div>

{% endblock %}

{% block page_js %}

<script type="text/javascript">

pr.controller('GetStartedController', ['$scope', '$http', '$location', 
	function ($scope, $http, $location) {

	$scope.init = function() {
		console.log("hello world!");
		$scope.ppid = 0;
		$scope.ccid = 0;
		$scope.planamount = 0;
		$scope.netamount = 0;
		$scope.coupon_discount = 0;
		$scope.show_coupon_message = false;
		$scope.coupon_disabled = true;

		$scope.is_this_step1 = false;
        $scope.is_this_step2 = true;
        $scope.is_this_step3 = true;
	}
	$scope.init();

	$scope.buynow = function(pk) {
		console.log(pk);
		var ppid = $("#"+pk).find("option:selected").val();
		var price = $("#"+pk).find("option:selected").data("price");
		console.log("PPID :"+ ppid);
		$scope.ppid = ppid;
		$scope.planamount = price;
		$scope.netamount = $scope.planamount - $scope.coupon_discount;
		$scope.coupon_disabled = false;
	}

	$scope.applyCoupon = function(coupon) {
		$scope.show_coupon_message = true;
		url = "/subscriber/get-coupon/"+coupon+"/"
		$http.get(url).success(function(data){
			if (data != 'DoesNotExist') {
				console.log(data);
				$scope.ccid = data[0].pk;
				var discount = data[0].fields.discount_amount
				var discount_type = data[0].fields.discount_type

				if(discount_type == 0) {
					$scope.netamount = $scope.planamount - discount;
					$scope.coupon_message = "You availed $"+ discount +" discount";
				} else if (discount_type == 1) {
					var disc = ($scope.planamount * discount)/100;
					$scope.netamount = $scope.planamount - disc;
					$scope.coupon_message = "You availed $"+ disc +" discount";
				}
			} else {
				$scope.coupon_message = "Your coupon is not valid for discount";
			}
			

		}).error(function(err){

		});

		
		
	}

}]);

</script>

{% endblock %}

templates/subscriber/payment-details.html
<div class="col-md-6 col-md-offset-5">
	<table class="table payment">
		<thead>
			<tr>
				<th width="50%"><h1>Payment Details</h1></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Plan amount</td>
				<td>$ <span class="plan-amount">{[{planamount}]}</span></td>
			</tr>
			<tr>
				<td>Do you have a coupon code?</td>
				<td> 
					<div class="input-group">
						<input type="text" name="coupon" class="form-control" ng-model="coupon" ng-disabled="coupon_disabled">
						<span class="input-group-btn">
							<button class="btn btn-danger"  type="button" ng-click="applyCoupon(coupon)"
							ng-disabled="coupon_disabled">Apply</button>
						</span>
					</div>
					<div class="message bg-info" ng-show="show_coupon_message">{[{ coupon_message }]}</div>
				</td>
			</tr>
			<tr>
				<td>Net amount</td>
				<td>$ <span class="net-amount">{[{netamount}]}</span></td>
			</tr>
		</tbody>
		<tfoot>
			<tr>
				<td></td>
				<td style="text-align: right;">
				<form action="/subscriber/payment/create/" method="post">{% csrf_token %}
					<input type="hidden" value="{[{ppid}]}" name="ppid">
					<input type="hidden" value="{[{ccid}]}" name="ccid">
					<input type="hidden" value="{[{planamount}]}" name="plan_amount">
					<input type="hidden" value="{[{netamount}]}" name="net_amount">
					<button class="btn btn-primary btn-lg" type="submit">Checkout</button>
				</form>
				</td>
			</tr>
		</tfoot>

		
	</table>
</div>

templates/subscriber/plan.html
<div class="col-md-10 col-md-offset-1">
	
	<table class="table plan">
		<thead>
			<tr>
				<th width="500">Plan Comparison</th>
				{% for plan in packages %}
					<th width="200">{{ plan.package_name }}</th>
				{% endfor %}
			</tr>
		</thead>
		<tbody>
			{% for service in services %}
				<tr>
					<td>{{ service.name }}</td>
					{% for plan in packages %}

							{% if plan in service.package_set.all %}
								<td class="custom-border"> 
									<input type="checkbox" checked onclick="return false"> 
								</td>
							{% else %}
								<td class="custom-border"> 
									<input type="checkbox" onclick="return false"> 
								</td>
							{% endif %}

					{% endfor %}
					
				</tr>
			{% endfor %}
			{% for frequency in frequencies %}
				<tr>
					<td> {{ frequency }}</td>
					{% for plan in packages %}
						{% for pp in package_plans %}
							
							{% if plan == pp.package and frequency == pp.frequency %}
								<td class="custom-border"> ${{ pp.price }}</td>
							{% endif %}

						{% endfor %}	
					{% endfor %}
					
				</tr>
			{% endfor %}
		</tbody>
		<tfoot>
			<tr>
				<td></td>
				{% for pk in packages %}
				<td class="custom-border">
					<select class="form-control" id="{{pk}}">
					
						{% for freq in frequencies %}
						
							{% for pp in package_plans %}
								{% if pk == pp.package and freq == pp.frequency %}
									<option value="{{pp.id}}" data-price="{{pp.price}}">{{ freq }}</option>
								{% endif %}
							{% endfor %}
						{% endfor %}	
					

					</select>
					<div style="margin-top:10px;">
					<button class="btn btn-danger" role="group"  ng-click="buynow('{{pk}}')">Buy Now</button>
					</div>
				</td>
				
				{% endfor %}
				
			</tr>
			
		</tfoot>
	</table>
</div>

templates/subscriber/supplier-login.html
{% extends "layout.html" %}
{% block logintop %}
{% endblock %}

{% block container %}
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="jumbotron">
			<form name="loginForm" action="/subscriber/login/" method="post">{% csrf_token %}
				<table class="table">
					<tr>
						<td colspan="3"><span class="tableHeadingTxt">Login to Procurement Registration</span></td>
					</tr>
					<tr>
						<td>
							<input type="text" class="form-control" name="username" placeholder="Username"/>
						</td>
						<td>
							<input type="password" class="form-control" name="password" placeholder="Password"/>
						</td>
						<td>
							<button class="btn btn-primary" type="submit">Sign In</button>
						</td>

					</tr>
					<tr>
						<td colspan="3"><a href="/subscriber/forget-password/" id="forgotPassword">Forgot Password</a></td>
					</tr>
				</table>
			</form>
		</div>		
	</div>
</div>

{% endblock container %}

templates/subscriber/supplier-registration.html
{% extends "layout.html" %}

{% block container %}
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="jumbotron">
			<form name="registrationForm" action="/subscriber/registration/" method="post" novalidate>{% csrf_token %}
				<table class="table">
					<tr>
						<th>Get started now in 3 simple steps</th>
					</tr>
					<tr>
						<td>
							<input type="text" class="form-control " name="username" placeholder="Username" required>
						</td>
					</tr>
					<tr>
						<td>
							<input type="email" class="form-control " name="email" placeholder="Email" required>
						</td>
					</tr>
					<tr>
						<td>
							<input type="password" ng-model="password1" class="form-control " name="password1" placeholder="Password" required>
						</td>
					</tr>
					<tr>
						<td>
							<input type="password" ng-model="password2" class="form-control " name="password2" placeholder="Confirm Password">
						</td>
					</tr>
					<tr>
						<td>
							<input type="checkbox" class="" name="terms" required> I agree to the terms and conditions
						</td>
					</tr>
					<tr>
						<td>
							<input type="submit" class="btn btn-primary btn-lg btn-block" value="Register" ng-disabled="registrationForm.$invalid" >
						</td>
					</tr>
				</table>
			</form>
		</div>		
	</div>
</div>

{% endblock container %}