pr3/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'pr3.views.home', name='home'),
    # url(r'^login/$', 'pr3.views.supplierlogin', name='login'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^blog/', include('blog.urls')),
    url(r'^subscriber/', include('subscriber.urls')),
    url(r'^supplier/', include('supplier.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

supplier/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:


    url(r'^profile/$', 'supplier.views.supplier_profile', name='supplier-profile'),
    url(r'^profile/api/(?P<id>\d+)/$', 'supplier.views.supplier_profile_json', name='supplier-profile-json'),
    url(r'^profile/info/$', 'supplier.views.supplier_profile', name='supplier-profile'),
    
    url(r'^profile/company/info/$', 'supplier.views.comapny_info', name='comapny-info'),
    url(r'^profile/company/info/api/(?P<supplier_id>\d+)/$', 'supplier.views.comapny_info_json', name='comapny-info-json'),
    
    url(r'^profile/company/revenue/$', 'supplier.views.company_revenue', name='company-revenue'),
    url(r'^profile/company/revenue/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_revenue_json', name='company-revenue-json'),

    url(r'^profile/company/contacts/$', 'supplier.views.company_contacts', name='company-contacts'),
    url(r'^profile/company/licenses/$', 'supplier.views.company_licenses', name='company-licenses'),
    url(r'^profile/company/licenses/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_licenses_json', name='company-licenses-json'),
    url(r'^profile/company/products-services/$', 'supplier.views.company_products_services', name='company-products-services'),
    url(r'^profile/company/products-services/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_products_services_json',
                                                                    name='company-product-services-json'),
    url(r'^profile/company/certification/$', 'supplier.views.company_certification', name='company-certification'),
    url(r'^profile/company/certification/api/(?P<supplier_id>\d+)/$', 'supplier.views.company_certification_json',
                                                                    name='company-certification-json'),


    url(r'^search-corporation/$', 'supplier.views.search_corporation', name='search-corporation'),
    url(r'^search_buyers/$', 'supplier.views.search_buyers', name='search-buyers'),
    url(r'^save_buyers/$', 'supplier.views.save_buyers', name='save-buyers'),
    url(r'^delete_buyer/$', 'supplier.views.delete_buyer', name='delete-buyers'),
    url(r'^add_manual_buyer/$', 'supplier.views.add_manual_buyer', name='add-manual-buyers'),

    url(r'^search/buyer/$', 'supplier.views.search_buyer', name='search-buyer'),
    url(r'^submission-status/$', 'supplier.views.supplier_submission_status', name='submission-status'),

    # url(r'^search-corporation/$', 'supplier.views.search_corporation', name='search-corporation'),
    
)

supplier/models.py
from django.db import models
from django.contrib.auth.models import User
from supplier.choices import *
from decimal import Decimal
# Create your models here.
class ProductAndServiceCategory(models.Model):
    '''
    Product category 
    '''
    category_name = models.CharField(max_length=256, blank=True, null=True, verbose_name='Category Name')

    def __unicode__(self):
        return self.category_name

class ProductServiceCode(models.Model):
    '''
    This model will take SIC, NAICS etc code.
    code_type = SERVICE_CODE_TYPE
    '''
    code = models.CharField(max_length=50, blank=True, null=True, verbose_name='Code', unique=True)
    code_type = models.CharField(max_length=15, choices=SERVICE_CODE_TYPE, blank=True, null=True, verbose_name='Code Type')
    title = models.CharField(max_length=50, blank=True, null=True, verbose_name='Title')
    common_keywords = models.CharField(max_length=200, blank=True, null=True, verbose_name='Common Keywords')
    category = models.ForeignKey(ProductAndServiceCategory, blank=True, null=True)

    def __unicode__(self):
        return "%s: %s" % (self.code_type, self.code)


class Buyer(models.Model):
    company_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Company Name')
    login_url = models.URLField(max_length=256, blank=True, null=True, verbose_name='Login Url')
    registration_url = models.URLField(max_length=256, blank=True, null=True, verbose_name='Registration Url')
    buyer_introduction = models.CharField(max_length=500, blank=True, null=True, verbose_name='Buyer Introduction')
    state = models.CharField(max_length=100, blank=True, null=True, verbose_name='State')
    ps_buy_code = models.ManyToManyField(ProductServiceCode, blank=True, null=True, related_name='comp_buy_codes')
    product_service_category = models.ManyToManyField(ProductAndServiceCategory, blank=True, null=True)

    def __unicode__(self):
        return self.company_name

class Supplier(models.Model):
    user = models.OneToOneField(User)
    salutation = models.CharField(max_length=5, blank=True, null=True, verbose_name='Salutation')
    first_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='First Name')
    last_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Last Name')
    position = models.CharField(max_length=50, blank=True, null=True, verbose_name='Position')
    phone_number = models.CharField(max_length=25, blank=True, null=True, verbose_name='Phone Number')
    fax_number = models.CharField(max_length=25, blank=True, null=True, verbose_name='Fax Number')
    cell_number = models.CharField(max_length=25, blank=True, null=True, verbose_name='Cell Number')
    contact_email = models.EmailField(blank=True,null=True, verbose_name='Contact E-Mail')
    contact_address = models.CharField(max_length=500, blank=True,null=True, verbose_name='Contact Address')
    country = models.CharField(max_length=50, blank=True, null=True, verbose_name='Country')
    state = models.CharField(max_length=50, blank=True, null=True, verbose_name='State')
    city = models.CharField(max_length=50, blank=True, null=True, verbose_name='City')
    zip_code = models.CharField(max_length=15, blank=True, null=True, verbose_name='Zip Code')
    method_of_notification = models.CharField(max_length=10, blank=True, null=True, verbose_name='Method of Notification')
    preferred_password = models.CharField(max_length=128, blank=True, null=True, verbose_name='Password')
    subscription_status = models.CharField(max_length=10, blank=True, null=True, verbose_name='Subscription Status')
    subscription_date = models.DateField(blank=True, null=True)
    subscription_expire_date = models.DateField(blank=True, null=True)
    profile_completion_status = models.CharField(max_length=10, blank=True, null=True, verbose_name='Profile Completion Status') 

    def __unicode__(self):
        return str(self.id)

    def get_profile_completion_status_redirect_url(self):
        if int(self.profile_completion_status) == 1:
            redirect_url = "/supplier/profile/company/revenue/"
        elif int(self.profile_completion_status) == 2:
            redirect_url = "/supplier/profile/company/contacts/"
        elif int(self.profile_completion_status) == 3:
            redirect_url = "/supplier/profile/company/licenses/"
        elif int(self.profile_completion_status) == 4:
            redirect_url = "/supplier/profile/company/products-services/"
        elif int(self.profile_completion_status) == 5:
            redirect_url = "/supplier/profile/company/certification/"
        elif int(self.profile_completion_status) == 6:
            redirect_url = "/supplier/submission-status/"
        elif int(self.profile_completion_status) == 0:
            redirect_url = "/supplier/profile/company/info/"
        elif int(self.profile_completion_status) == -1:
            redirect_url = "/supplier/profile/info/"
        else:
            redirect_url = "/supplier/submission-status/"

        return redirect_url

    def is_profile_complete(self):
        if self.salutation == None or self.salutation == '':
            return False
        elif self.first_name == None or self.first_name == '':
            return False
        elif self.last_name == None or self.last_name == '':
            return False
        elif self.position == None or self.position == '':
            return False
        elif self.phone_number == None or self.phone_number == '':
            return False
        elif self.cell_number == None or self.cell_number == '':
            return False
        elif self.contact_email == None or self.contact_email == '':
            return False
        elif self.contact_address == None or self.contact_address == '':
            return False
        elif self.country == None or self.country == '':
            return False
        elif self.state == None or self.state == '':
            return False
        elif self.city == None or self.city == '':
            return False
        elif self.preferred_password == None or self.preferred_password == '':
            return False
        else:
            return True


    def get_full_name(self):
        name = self.salutation
        if self.first_name:
            name += " " + self.first_name
        if self.last_name:
            name += " " + self.last_name
        return name

class CompanyCapabilityStatement(models.Model):
    capability_statement = models.TextField(max_length=250, blank=True, null=True, verbose_name='Capability Statement')
    upload_doc = models.FileField(blank=True, null=True, verbose_name='Document Upload',
        upload_to='attachment/doc')
    upload_video = models.CharField(max_length=250, blank=True, null=True)

    def __unicode__(self):
        return "%s" % (self.capability_statement[:20])
   

class Address(models.Model):
    address_title = models.CharField(max_length=200, blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    zip_code = models.CharField(max_length=50, blank=True, null=True)
    address_type = models.CharField(max_length=5, blank=True, null=True)

    def __unicode__(self):
        return "%s->%s" % (self.country, self.city)


class SupplierCompany(models.Model):
    supplier = models.OneToOneField(Supplier)
    comp_name = models.CharField(max_length=200, blank=True, null=True, verbose_name='Legal Company Name')
    organization_type = models.CharField(max_length=50, blank=True, null=True, verbose_name='Organization Type')
    doing_business_as = models.CharField(max_length=200, blank=True, null=True, verbose_name='DBA Company Name')
    tax_id_number = models.CharField(max_length=50, blank=True, null=True, verbose_name='Federal Tax ID')
    social_security_number = models.CharField(max_length=50, blank=True, null=True, verbose_name='Social Security Number')
    comp_dunn_street = models.CharField(max_length=50, blank=True, null=True, verbose_name='Dunn & Brad Street Number')
    comp_phone = models.CharField(max_length=20, blank=True, null=True, verbose_name='Company Phone Number')
    comp_fax = models.CharField(max_length=20, blank=True,null=True, verbose_name='Company Fax Number')
    comp_url = models.CharField(max_length=100, blank=True,null=True, verbose_name='Company Website (URL)')
    corporate_email = models.EmailField(blank=True,null=True, verbose_name='Corporate E-Mail')
    year_established = models.DateField(max_length=15,null=True, blank=True, verbose_name='Year Business was Established')
    num_of_employees = models.CharField(max_length=10,null=True, blank=True, verbose_name='Number Of Employees')
    # country = models.CharField(max_length=96, blank=True, null=True, verbose_name='Country')
    # state = models.CharField(max_length=96, blank=True, null=True, verbose_name='State')
    capability = models.ForeignKey(CompanyCapabilityStatement, blank=True, null=True)
    ps_categories = models.ManyToManyField(ProductAndServiceCategory, blank=True, null=True)
    product_service_description = models.TextField(max_length=200, blank=True,null=True, verbose_name='Product & Service Description')
    comp_logo = models.ImageField(blank=True, null=True, verbose_name='Current Company Logo', 
        upload_to='attachment/company/')
    comp_picture = models.ImageField(blank=True, null=True, verbose_name='Current Company/Personal Picture',
        upload_to='attachment/company/')
    comp_address = models.ForeignKey(Address, blank=True, null=True)

    def __unicode__(self):
        return str(self.id)
    


class CompanyRevenue(models.Model):
    company = models.OneToOneField(SupplierCompany)
    last_year_annual_sale = models.CharField(max_length=10, blank=True, null=True)

supplier/forms.py
from django import forms
from supplier.models import *

class ProfileForm(forms.ModelForm):

	class Meta:
		model = Supplier
		exclude = ['subscription_status', 'profile_completion_status']


class CompInfoForm(forms.ModelForm):
	class Meta:
		model = SupplierCompany


class CapabilityForm(forms.ModelForm):
	class Meta:
		model = CompanyCapabilityStatement


class RevenueForm(forms.ModelForm):
	class Meta:
		model = CompanyRevenue
		exclude = ['company',]

class AddressForm(forms.ModelForm):
	class Meta:
		model = Address

class CompanyLicenseForm(forms.ModelForm):
	class Meta:
		model = CompanyLicense
        exclude = ['company',]

class CompanyCertificationForm(forms.ModelForm):
	class Meta:
		model = CompanyCertification
        exclude = ['company',]

class CertificateNameForm(forms.ModelForm):
	class Meta:
		model = CertificateName
        exclude = ['display_order','active']

class CompanyProductServiceForm(forms.ModelForm):
    class Meta:
        model = CompanyProductService
        exclude = ['company',]

templates/supplier/form/company_contact_form.html
<div class="row" ng-controller="CompContactController">
<div class="col-md-10">
	<form noviolate name="comp_contact_form" action="/supplier/profile/company/contacts/" method="post">{% csrf_token %}
	<input type="hidden" name="user" id="id_user" value="{{user.id}}">
	<input type="hidden" name="supplier" id="id_supplier" value="{{supplier.id}}">
	<input type="hidden" name="company" id="id_company" value="{{company.id}}">
		<table class="table">
		<tbody id="company_contact">
			<tr>
				<th width="250">
					<label for="id_name">Contact Name</label>
				</th>
				<td>
					<input type="text" class="form-control" name="name" id="id_name" value="{[{comp_contact.name}]}"> 
						<div ng-show="comp_contact_form.$dirty && comp_contact_form.name.$error.required && comp_contact_form.name.$touched">
							<p  class="bg-warning">Please enter contact name.</p>
						</div>
				</td>
				
			</tr>
			<tr>
				<th width="250">
					<label for="id_title">Contact Title</label>
				</th>
				<td>
					<input type="text" class="form-control" name="title" id="id_title" value="{[{comp_contact.title}]}"> 
						<div ng-show="comp_contact_form.$dirty && comp_contact_form.title.$error.required && comp_contact_form.title.$touched">
							<p  class="bg-warning">Please enter contact title.</p>
						</div>
				</td>
				
			</tr>

			<tr>
				<th width="250">
					<label for="id_phone">Contact Phone</label>
				</th>
				<td>
					<table class="table innertable">
						<tr>
							<td width="70%">
								<input type="text" class="form-control" name="phone" id="id_phone" value="{[{comp_contact.phone}]}">
								<div ng-show="comp_contact_form.$dirty && comp_contact_form.phone.$error.required && comp_contact_form.phone.$touched">
									<p  class="bg-warning">Please enter contact phone.</p>
								</div>	
							</td>
							<td>
								Ext.
							</td>
							<td>
								<input type="text" class="form-control" name="phone_ext" id="id_phone_ext" value="{[{comp_contact.phone_ext}]}">	
							</td>
						</tr>
					</table>
					
				</td>
				
			</tr>

			<tr>
				<th width="250">
					<label for="id_fax">Fax</label>
				</th>
				<td>
					<input type="text" class="form-control" name="fax" id="id_fax" value="{[{comp_contact.fax}]}">
				</td>
				
			</tr>
			<tr>
				<th><label for="id_email">Email</label></th>
				<td>
					<input type="email" id="id_email" name="email" ng-model="comp_contact.email" class="form-control" value="{[{comp_contact.email}]}" required autocomplete="off"> 
						
						<div ng-show="comp_contact_form.$dirty && comp_contact_form.email.$error.required && comp_contact_form.email.$touched">
							<p  class="bg-warning">Please enter contact email id.</p>
						</div>
						<div ng-show="comp_contact_form.$dirty && comp_contact_form.email.$error.email && comp_contact_form.email.$touched">
							<p  class="bg-warning">Please enter a valid email </p>
						</div>
				</td>
			</tr>
			</tbody>
			</table>
			<tr>
				<td colspan="2" class="bg-info">
					References
				</td>
			</tr>
			<table class="table" style="border: 1px solid #CCC;">
				<tr>
					<th width="250">
						<label for="id_company_name">Company Name</label>
					</th>
					<td>
						<input type="text" class="form-control" name="company_name" id="id_company_name" value="{[{comp_contact.company_name}]}"> 
						<div ng-show="comp_contact_form.$dirty && comp_contact_form.name.$error.required && comp_contact_form.name.$touched">
							<p  class="bg-warning">Please enter company name.</p>
						</div>
					</td>
					
				</tr>

				<tr>
					<th width="250">
						<label for="id_contact_name">Contact Name</label>
					</th>
					<td>
						<input type="text" class="form-control" name="contact_name" id="id_contact_name" value="{[{comp_contact.contact_name}]}"> 
						<div ng-show="comp_contact_form.$dirty && comp_contact_form.contact_name.$error.required && comp_contact_form.contact_name.$touched">
							<p  class="bg-warning">Please enter contact name.</p>
						</div>
					</td>
					
				</tr>

				<tr>
					<th width="250">
						<label for="id_phone">Phone</label>
					</th>
					<td>
						<input type="text" class="form-control" name="phone" id="id_phone" value="{[{comp_contact.phone}]}"> 
						<div ng-show="comp_contact_form.$dirty && comp_contact_form.phone.$error.required && comp_contact_form.phone.$touched">
							<p  class="bg-warning">Please enter phone number</p>
						</div>
					</td>
					
				</tr>

				<tr>
					<th width="250">
						<label for="id_email">Email</label>
					</th>
					<td>
						<input type="text" class="form-control" name="email" id="id_email" value="{[{comp_contact.email}]}"> 
						<div ng-show="comp_contact_form.$dirty && comp_contact_form.email.$error.required && comp_contact_form.email.$touched">
							<p  class="bg-warning">Please enter email id</p>
						</div>
					</td>
					
				</tr>

				<tr>
					<th width="250">
						<label for="id_services_provided">Service Provided</label>
					</th>
					<td>
						<input type="text" class="form-control" name="services_provided" id="id_services_provided" value="{[{comp_contact.services_provided}]}"> 
						<div ng-show="comp_contact_form.$dirty && comp_contact_form.services_provided.$error.required && comp_contact_form.services_provided.$touched">
							<p  class="bg-warning">Please enter the service provided</p>
						</div>
					</td>
					
				</tr>
			</table>

		<table class="table">
			<tr>
				<th colspan="2">
					<button class="btn btn-primary">Save & Continue</button>
				</th>
			</tr>

		</table>
	</form>
</div>
</div>

templates/supplier/form/company_info_form.html
<div class="row" ng-controller="CompInfoController">
<div class="col-md-10">
	<form novalidate name="comp_form" action="/supplier/profile/company/info/" method="post">{% csrf_token %}
	<input type="hidden" name="user" id="id_user" value="{{user.id}}">
	<input type="hidden" name="supplier" id="id_supplier" value="{{supplier.id}}">
		<table class="table">
		<tbody>
			<tr>
				<th width="200"><label for="id_comp_name">Comapny Name</label></th>
				<td>
					<input type="text" id="id_comp_name" name="comp_name" ng-model="comp.comp_name" class="form-control" value="{[{comp.comp_name}]}" required autocomplete="off"> 

					<div ng-show="comp_form.$dirty && comp_form.comp_name.$error.required && comp_form.comp_name.$touched">
						<p  class="bg-warning">Please enter your company name.</p>
					</div>
				</td>
			</tr>
			<tr>
				<th><label for="id_organization_type">Organization Type</label></th>
				<td>
					<input type="text" id="id_organization_type" name="organization_type" ng-model="comp.organization_type" class="form-control" placeholder="Please put 'N/A' if no value available" value="{[{comp.organization_type}]}" required autocomplete="off"> 

					<div ng-show="comp_form.$dirty && comp_form.organization_type.$error.required && comp_form.organization_type.$touched">
						<p  class="bg-warning">Please select organization type.</p>
					</div>

				</td>
			</tr>
			<tr>
				<th><label for="id_doing_business_as">Doing Business As</label></th>
				<td>
					<input type="text" id="id_doing_business_as" name="doing_business_as" ng-model="comp.doing_business_as" class="form-control" placeholder="Please put 'N/A' if no value available" value="{[{comp.doing_business_as}]}" required autocomplete="off"> 

					<div ng-show="comp_form.$dirty && comp_form.doing_business_as.$error.required && comp_form.doing_business_as.$touched">
						<p  class="bg-warning">Please enter your DBA.</p>
					</div>

				</td>
			</tr>
			<tr>
				<th><label for="id_tax_id_number">Federal Tax ID Number</label></th>
				<td>
					<input type="text" id="id_tax_id_number" name="tax_id_number" ng-model="comp.tax_id_number" class="form-control" placeholder="Please put 'N/A' if no value available" value="{[{comp.tax_id_number}]}" required autocomplete="off"> 

					<div ng-show="comp_form.$dirty && comp_form.tax_id_number.$error.required && comp_form.tax_id_number.$touched">
						<p  class="bg-warning">Please enter your federal tax ID.</p>
					</div>

				</td>
			</tr>
			<tr>
				<th><label for="id_social_security_number">Social Security Number</label></th>
				<td>
					<input type="text" id="id_social_security_number" name="social_security_number" ng-model="comp.social_security_number" class="form-control"  placeholder="Please put 'N/A' if no value available" value="{[{comp.social_security_number}]}" required autocomplete="off">

					<div ng-show="comp_form.$dirty && comp_form.social_security_number.$error.required && comp_form.social_security_number.$touched">
						<p  class="bg-warning">Please enter your SSN.</p>
					</div> 
				</td>
			</tr>
			<tr>
				<th><label for="id_comp_dunn_street">Dunn & Brad Street Number</label></th>
				<td>
					<input type="text" id="id_comp_dunn_street" name="comp_dunn_street" ng-model="comp.comp_dunn_street" class="form-control"  placeholder="Please put 'N/A' if no value available" value="{[{comp.comp_dunn_street}]}" required autocomplete="off"> 

					<div ng-show="comp_form.$dirty && comp_form.comp_dunn_street.$error.required && comp_form.comp_dunn_street.$touched">
						<p  class="bg-warning">Please enter your DunB number.</p>
					</div>

				</td>
			</tr>
			<tr>
				<th><label for="id_comp_phone">Company Phone Number</label></th>
				<td>
					<input type="text" id="id_comp_phone" name="comp_phone" ng-model="comp.comp_phone" class="form-control"  placeholder="Please put 'N/A' if no value available" value="{[{comp.comp_phone}]}" required autocomplete="off"> 

					<div ng-show="comp_form.$dirty && comp_form.comp_phone.$error.required && comp_form.comp_phone.$touched">
						<p  class="bg-warning">Please enter your company name.</p>
					</div>

				</td>
			</tr>
			<tr>
				<th><label for="id_comp_fax">Company Fax Number</label></th>
				<td>
					<textarea id="id_comp_fax" name="comp_fax"  placeholder="Please put 'N/A' if no value available" ng-model="comp.comp_fax" class="form-control" value="{[{comp.comp_fax}]}" required autocomplete="off">
						
					</textarea>
					<div ng-show="comp_form.$dirty && comp_form.comp_fax.$error.required && comp_form.comp_fax.$touched">
						<p  class="bg-warning">Please enter your company fax number.</p>
					</div>
				</td>
			</tr>
			<tr>
				<th><label for="id_corporate_email">Corporate Email</label></th>
				<td>
					<input type="email" id="id_corporate_email" name="corporate_email" ng-model="comp.corporate_email" class="form-control" value="{[{comp.corporate_email}]}" required autocomplete="off"> 
					<div ng-show="comp_form.$dirty && comp_form.corporate_email.$error.required && comp_form.corporate_email.$touched">
						<p  class="bg-warning">Please enter your company email id.</p>
					</div>
				</td>
			</tr>

			<tr>
				<th><label for="id_comp_url">Company Website</label></th>
				<td>
					<input type="url" id="id_comp_url" name="comp_url" ng-model="comp.comp_url" class="form-control" value="{[{comp.comp_url}]}" required autocomplete="off"> 
					<div ng-show="comp_form.$dirty && comp_form.comp_url.$error.required && comp_form.comp_url.$touched">
						<p  class="bg-warning">Please enter your company website url.</p>
					</div>
				</td>
			</tr>
			
			<tr>
				<th><label for="id_year_established">Year Established</label></th>
				<td>
					<input type="text" id="id_year_established" name="year_established" ng-model="comp.year_established" class="form-control datetime"  placeholder="Please put 'N/A' if no value available" value="{[{comp.year_established}]}" required autocomplete="off"> 
					<div ng-show="comp_form.$dirty && comp_form.year_established.$error.required && comp_form.year_established.$touched">
						<p  class="bg-warning">Please enter your company start date/year.</p>
					</div>
				</td>
			</tr>
			<tr>
				<th><label for="id_num_of_employees">Number of Employees</label></th>
				<td>
					<input type="text" id="id_num_of_employees" name="num_of_employees" class="form-control"  placeholder="Please put 'N/A' if no value available" ng-model="comp.num_of_employees" value="{[{comp.num_of_employees}]}"  required autocomplete="off"> 
					<div ng-show="comp_form.$dirty && comp_form.num_of_employees.$error.required && comp_form.num_of_employees.$touched">
						<p  class="bg-warning">Please enter your company employee range.</p>
					</div>
				</td>
			</tr>
			
			<tr>
				<th colspan="2" class="bg-danger">
					Company Capability Statement
				</th>
			</tr>
			<tr>
				<th><label for="id_capability_statement">Statement</label></th>
				<td>
					<textarea id="id_capability_statement" name="capability_statement" ng-model="comp.capability.capability_statement" class="form-control" placeholder="Please put 'N/A' if no value available" autocomplete="off">
						{[{comp.capability.capability_statement}]}
					</textarea>
				</td>
			</tr>
			<tr>
				<th><label for="id_upload_doc">Upload Document</label></th>
				<td>
					<input id="id_upload_doc" name="upload_doc" type="file" value="{[{capability.upload_doc}]}">
					<a href="" ng-show="capability.upload_doc">x</a>
				</td>
			</tr>
			<tr>
				<th>
					<label for="id_upload_video">Upload Video</label>
				</th>
				<td>
					<div class="input-group">
						<input id="id_upload_video" name="upload_video" type="text" value="{[{capability.upload_video}]}" class="form-control" autocomplete="off">
						<span class="input-group-btn">
				        	<button class="btn btn-danger" type="button">Show Video</button>
				      	</span>
					</div>
				</td>
			</tr>
			<tr>
				<th colspan="2" class="bg-danger">
					Company Product & Service Categories
				</th>
			</tr>
			<tr>
				<th><label for="id_product_service_description">Product & Service Description</label></th>
				<td>
					<textarea id="id_product_service_description" name="product_service_description" class="form-control" ng-model="comp.product_service_description"  placeholder="Please put 'N/A' if no value available" autocomplete="off">
						{[{comp.product_service_description}]}
					</textarea>
				</td>
			</tr>
			<tr>
				<th><label for="id_product_service_description">Product & Service Category</label></th>
				<td>
					<select id='pre-selected-options' multiple='multiple' name="ps_categories" ng-model="comp.categories">
						<option value="-1">None</option>
						{% for cat in ps_categories %}
							<option value="{{cat.id}}" {% if cat in selected_categories %} selected {% endif %}>{{cat}}</option>
						{% endfor %}
					</select>

					<div ng-show="comp_form.$dirty && comp_form.ps_categories.$error.required && comp_form.ps_categories.$touched">
						<p  class="bg-warning">Please select your company categories.</p>
					</div>
				</td>
			</tr>
			
		</tbody>
		<tfoot>
			<tr>
				<th colspan="2">
					<button class="btn btn-primary">Save & Continue</button>
				</th>
			</tr>
		</tfoot>

		</table>
	</form>
</div>
</div>

templates/supplier/form/search.html
<div class="row" ng-controller="SearchPageController">
{% include "supplier/right-side-content.html" %}
</div>